### ISSUE TITLE
Can't adjust mixing parameters

### ISSUE THREAD

**Issue by pedroaslongo** [smussmann82/BayesAss3-SNPs#12]
Dear Dr. Mussmann, 

I hope everything is fine with you. I would like to ask you for some help in using Bayesass3-SNPs, please. 

I've been trying to run this on Ubuntu on a dataset of four species, with 513, 148, 328 and 248 SNPs respectively. I've been trying to adjust the parameters 1, 3 and 4 to get accaptance rates between 20-60%, by increasing the proposal step lengths, as recommended in the manual, however for three of the species, mixing parameters continue higher than 60% even after increasing step size up until 1,00. We checked for MCMC diagnostics using trace plots, and it seems fine. 
For those three species, one of them presented a genetic structure while the other two did not have structured populations. For all three species, migrations rates among localities were very low.

Would you say these results can be confiable? Is there any other way that I could adequately adjust mixing parameters in order to get better results? 

This was the final command line I used for the analysis: 

BA3-SNPS -v -F Pinctada_bayesass.immanc -l 328 -m 1.00 -a 1.00 -f 1.00 -t -s 100 -i10000000 -b1000000

Thank you very much!

Best regards,
Pedro

**Comment by stevemussmann** [comment]
Hi Pedro,

It sounds like everything is fine to me. In my experience it is rare, but possible, that you will run into some datasets that cannot be fully tuned to get acceptance rates within the 20-60% range. When that happens, you may sometimes have to run the MCMC chains longer to get an adequate effective sample size, but, it looks like you are already doing 10 million generations, so you are probably OK. 

-Steve
