### ISSUE TITLE
Does BA3-SNPs require bi-allelic loci?

### ISSUE THREAD

**Issue by jzhan6** [smussmann82/BayesAss3-SNPs#13]
I am new to the BA3 and I feel the inputs for this software should be all bi-allelic loci. Am I correct?

**Comment by stevemussmann** [comment]
It can handle >2 alleles per locus.

**Comment by jzhan6** [comment]
Thanks for prompt reply. So all loci for BA3 should have more than 2 alleles and loci with only one allele should be removed from input for BA3?

**Comment by stevemussmann** [comment]
I would recommend removing any loci with a single allele since they will not be informative and will only increase computation time and memory usage.

**Comment by jzhan6** [comment]
Thanks for your reply. I ran the BA3-SNPs, but I am a bit confused with the results.  We want to calculate the migration rates between samples from several localities of the same species. All migrations are around 0.01, eg: 0.012, 0.008 and even for samples at the nearly same locality although different years, their migration rate is around 0.01 not higher than that between samples at far away localities. The results make me extremely confused. For most locality, we have 3 samples but we can around 5000 SNPs although data for samples samples are missing in some loci. Does this happen due to small sample size?

**Comment by stevemussmann** [comment]
This paper has some information that might be useful to you. There are a lot of properties of a dataset that can influence BayesAss results:

https://onlinelibrary.wiley.com/doi/abs/10.1111/j.1365-294X.2007.03218.x
