### ISSUE TITLE
Priors on migration rates limited to 2/3 (lower values)

### ISSUE THREAD

**Issue by marianamazzochi** [smussmann82/BayesAss3-SNPs#14]
Dear Steve,
I am using BayesAss-SNPs to estimate migration rates of 6 populations of seabirds. Other methods indicate a lot of migration among the studied populations. It seems that my posterior distributions of m[i,i] get stacked at the lower limit of 0,67. I wonder if it would be possible to relax the prior constrains on m values. Could you help me?

Regards,
Mariana Mazzochi

**Comment by stevemussmann** [comment]
Hi Mariana,

Apologies for the late response; I've been crazy busy lately and haven't been able to keep on top of some issues with my software packages.

It appears you are running into an issue that can't be easily resolved, for reasons outlined in the introduction of this paper (https://onlinelibrary.wiley.com/doi/10.1111/1755-0998.12216). Meirmans, P.G. (2014), Nonconvergence in Bayesian estimation of migration rates. Mol Ecol Resour, 14: 726-733. https://doi.org/10.1111/1755-0998.12216

I wish I had a better answer for you, but unfortunately BayesAss assumes a relatively low migration rate, so it might not be appropriate for your dataset if you know you have a high migration rate among populations. 

-Steve
