### ISSUE TITLE
Installation problems (docker)

### ISSUE THREAD

**Issue by quinn-ca** [smussmann82/BayesAss3-SNPs#15]
Hello,

I'm looking forward to running this software, however, I'm having difficulty with the installation. I'm installing via Docker to ensure I have all the dependencies, and this is my first time using this program. Everything seems to have gone correctly, using `pull` to install, then executing `runDocker.sh`. This does indeed create a `data` folder.

However, I'm confused about the line in the ReadMe, "In addition to BA3-SNPs, the countLociImmanc.sh script, BA3-SNPS-autotune, and file conversion scripts (stacksStr2Immanc.pl and pyradStr2Immanc.pl) are also installed in your $PATH in this container." I don't see these scripts in the 'data' folder where I executed runDocker.sh, or the `/apps/data` folder. If they are installed elsewhere, they don't seem to be accessible on my path. I ran `/countLociImmanc.sh -f autosomal_genstr_filtered_maxMeanDP49_rmRelated.immanc` from both `data` folders mentioned above and got the error:

./countLociImmanc.sh: No such file or directory

Should I be installing these scripts separately? I thought these would be installed using Docker, but I'm new to this method for installing programs. I sincerely appreciate any help you can provide!

Quinn

**Comment by stevemussmann** [comment]
Hi Quinn,

You should be able to run the script in the Docker container without specifying the script's location. In other words, you should be able to run `countLociImmanc.sh -f autosomal_genstr_filtered_maxMeanDP49_rmRelated.immanc` without specifying `./` in front of the script name.

**Comment by quinn-ca** [comment]
Thank you! What a refreshingly straightforward fix; it worked and returned the expected number of loci. 

Cheers,
Quinn
