### ISSUE TITLE
Parallelization

### ISSUE THREAD

**Issue by githubgig** [smussmann82/BayesAss3-SNPs#16]
Hello,

I'm running BA3 using parallel, but it is using only 2 threads even when I specify -j 20. Is there a better way to parallelize?

Thank you.

**Comment by stevemussmann** [comment]
Each instance of BA3 will run on a single core, so the number of threads in use will be determined by the number of instances of BA3 that are submitted to parallel simultaneously.

**Comment by githubgig** [comment]
Hi Steve, 

Thanks for the reply. I see. I'm guessing each instance is one run correct? I'm currently doing just one test run (10M iterations using a single command in the ba3_commands.txt). I was wondering if there is a way to parallelize within each run?

Thanks again.

**Comment by stevemussmann** [comment]
That is correct - each instance is one run. There is currently no way to parallelize within a run. It's on my 'to do' list but will require a significant code overhaul.

**Comment by githubgig** [comment]
I see. Thanks for your replies though.

**Comment by stevemussmann** [comment]
No problem. I'm going to close this issue but please feel free to open a new one if you run into problems.
